import liff, { init } from './liff'

export default async () => {
  const root = window.document.getElementById('root')
  if (!root) {
    throw new Error('this is unreached')
  }

  try {
    await init()

    const profile = await liff.getProfile()
    /*
       root.innerHTML = `
       <div>generated by liff-app-template</div>
       <div>${profile.displayName}</div>
       <img src=${profile.pictureUrl}>
       `
     */

    const image = document.getElementById('map');
    image.addEventListener("click", () => liff.sendMessages([
      { type:"text", text:"このプランにする" }
    ]));

    image.addEventListener("click", function() {
      liff.closeWindow();
    });
  }
  catch(error) {
    root.innerHTML = `<pre>${error}</pre>`
  }
}
