import liff, { init } from './liff'

export default async () => {
  const root = window.document.getElementById('root')
  if (!root) {
    throw new Error('this is unreached')
  }

  try {
    await init()

    const profile = await liff.getProfile()
    /*
       root.innerHTML = `
       <div>generated by liff-app-template</div>
       <div>${profile.displayName}</div>
       <img src=${profile.pictureUrl}>
       `
     */

    const image = document.getElementById('map');
    document.getElementById('success').style.display = "none";
    const complete = document.getElementById('success')

    map.addEventListener("click", function() {
      image.style.display = "none";
      complete.style.display = "block";
    });

    complete.addEventListener("click", function() {
      liff.sendMessages([ { type:"text", text:"LINE認証完了" } ]);
      liff.closeWindow();
    });
  }
  catch(error) {
    root.innerHTML = `<pre>${error}</pre>`
  }
}
